default_pulling_interval: 10
token: <COLLECTOR_TOKEN>
platform_host_url: http://localhost:8080
plugins:
  - type: clickhouse
    name: clickhouse_adapter
    host: localhost
    database: helloworld
    user: default
    password: qwerty
  - type: cubejs
    name: cubejs_adapter
    host: http://localhost:4000
    token: <CUBEJS_TOKEN>
    predefined_datasource:
      type: "clickhoust"
      host: localhost
      database: helloworld
