token: "WE3fO03LssZKjlPIgO07ABm6RlkI62hdIPxzaTOq"
platform_host_url: http://localhost:8081
chunk_size: 1000
plugins:
  - type: hive
    name: hive_adapter_new_2
    description: "" # Optional string
    host: 0.0.0.0
    port: 9083
    database: default