default_pulling_interval: 10
token: ""
platform_host_url: http://localhost:8080
plugins:
  - type: postgresql
    name: postgresql_adapter
    database: computer
    host: localhost
    port: 5432
    user: postgres
    password: ""
  - type: cubejs
    name: cubejs
    host: http://localhost:4000
    token: ""
    dev_mode: true
    predefined_datasource:
      type: "postgres"
      host: localhost
      database: computer