default_pulling_interval: 60 # in minutes. If not specified, collector will pull data once.
platform_host_url: http://localhost:8080
token: <token> # Required string, token for authentication
plugins:
  - type: postgresql
    name: postgresql_adapter
    description: "" # Optional string
    database: database
    host: host
    port: 5432
    user: user
    password: password