default_pulling_interval: 10
token: ""
platform_host_url: "http://localhost:8080"
plugins:
  - type: postgresql
    name: test_psql
    host: "database"
    port: 5432
    database: ""
    user: ""
    password: ""
  # - type: tarantool
  #   name: tarantool
  #   host: localhost
  #   port: 3301
  #   user: odd_adapter
  #   password: odd_adapter_password
