token: "StW4MpUiSEs2rTf3ijeJKrwexPaPLiHKa07FI6O7" # Optional string
platform_host_url: http://localhost:8080
chunk_size: 1000
plugins:
  - type: superset
    name: superset_adapter
    server: http://localhost:8088/
    username: admin
    password: admin