name: Build and publish PyPI artifact

on:
  workflow_dispatch:

jobs:
  build_and_publish_package:
    name: Build and publish the PyPi package
    runs-on: ubuntu-latest
    concurrency: publishing
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.1
          virtualenvs-create: false

      - name: Build and publish package into PyPI
        run: |
          poetry build
          poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
